# Generated by Django 2.1.1 on 2018-10-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('task', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
    ]
