# Generated by Django 2.1.1 on 2018-10-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_contactme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='Contact',
        ),
    ]
