# Generated by Django 2.1.1 on 2018-10-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20181016_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prof_image')),
                ('mar1', models.CharField(max_length=200)),
                ('mar2', models.CharField(max_length=200)),
                ('text', models.TextField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='about',
            name='text',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
