# Generated by Django 2.1.1 on 2018-10-17 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20181018_0010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='Home',
        ),
    ]
