# Generated by Django 2.1.1 on 2018-10-18 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0012_auto_20181018_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='text',
        ),
    ]
