# Generated by Django 2.1.1 on 2018-12-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0017_auto_20181025_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='agenda',
            field=models.TextField(default=''),
        ),
    ]
